// ============================================================
// Escalation Intelligence Platform — Mock Data
// ============================================================

import { Conversation, EvaluationMetrics, DashboardStats, AlertItem, TimeSeriesPoint, SignalFrequency, Ticket } from './types';

// Helper to create dates relative to now
const daysAgo = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
};

const hoursAgo = (hours: number) => {
  const d = new Date();
  d.setHours(d.getHours() - hours);
  return d;
};

const minutesAgo = (mins: number) => {
  const d = new Date();
  d.setMinutes(d.getMinutes() - mins);
  return d;
};

// ─── Sample Conversations ─────────────────────────────────────
export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_001',
    title: 'API Gateway 502 Errors',
    customer_name: 'Sarah Chen',
    category: 'Technical',
    status: 'escalated',
    created_at: hoursAgo(2),
    updated_at: minutesAgo(15),
    messages: [
      { id: 'm1', role: 'user', text: 'Our API gateway is returning 502 errors intermittently. This is causing significant revenue loss.', timestamp: hoursAgo(2) },
      { id: 'm2', role: 'agent', text: 'I understand the urgency. Can you share which endpoints are affected?', timestamp: hoursAgo(1.9) },
      { id: 'm3', role: 'user', text: 'All endpoints under /api/v2/payments. We\'ve been experiencing this for 3 hours now. This is the third time this month!', timestamp: hoursAgo(1.8) },
      { id: 'm4', role: 'agent', text: 'Let me check the server logs for that endpoint.', timestamp: hoursAgo(1.7) },
      { id: 'm5', role: 'user', text: 'We already checked logs. The issue is on your infrastructure side. We need this fixed NOW. Our customers are unable to make payments.', timestamp: hoursAgo(1.5) },
      { id: 'm6', role: 'agent', text: 'I see. Let me escalate this to our infrastructure team.', timestamp: hoursAgo(1.4) },
      { id: 'm7', role: 'user', text: 'This is unacceptable. We pay for premium support and this keeps happening. I want to speak with a manager.', timestamp: hoursAgo(1.2) },
    ],
    analysis: {
      risk: 0.92,
      priority: 'P1',
      predicted_escalation: true,
      detection_point: 3,
      emotion: 'ANGRY',
      root_cause: 'REPEATED_ISSUE',
      signals: { repetition: 2, resolution_failure: true, technical_issue: true, sentiment_score: -0.85, urgency: true },
      explanation: [
        'Customer has reported this issue multiple times ("third time this month")',
        'High urgency language detected ("NOW", "revenue loss")',
        'Resolution failure — no fix provided after multiple exchanges',
        'Extremely negative sentiment with escalation demand',
      ],
      suggested_actions: [
        'Immediately escalate to L3 Infrastructure team',
        'Check payment gateway cluster health',
        'Review recent deployment changes for /api/v2/payments',
        'Offer SLA credit for repeated incidents',
      ],
    },
  },
  {
    id: 'conv_002',
    title: 'Dashboard Loading Slowly',
    customer_name: 'Michael Torres',
    category: 'Performance',
    status: 'active',
    created_at: hoursAgo(4),
    updated_at: hoursAgo(1),
    messages: [
      { id: 'm1', role: 'user', text: 'Hey, our dashboard is taking 15+ seconds to load. It used to be instant.', timestamp: hoursAgo(4) },
      { id: 'm2', role: 'agent', text: 'Sorry to hear that. Which dashboard specifically?', timestamp: hoursAgo(3.9) },
      { id: 'm3', role: 'user', text: 'The analytics dashboard. It started after your last update.', timestamp: hoursAgo(3.8) },
      { id: 'm4', role: 'agent', text: 'I see. We did release an update yesterday. Let me look into any known performance issues.', timestamp: hoursAgo(3.7) },
      { id: 'm5', role: 'user', text: 'Any update on this? It\'s been an hour.', timestamp: hoursAgo(2.5) },
    ],
    analysis: {
      risk: 0.58,
      priority: 'P2',
      predicted_escalation: false,
      detection_point: 4,
      emotion: 'FRUSTRATED',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: true, sentiment_score: -0.3, urgency: false },
      explanation: [
        'Performance regression after recent update',
        'Customer follow-up indicates growing frustration',
        'No resolution provided yet',
      ],
      suggested_actions: [
        'Check analytics query performance post-update',
        'Review database query execution plans',
        'Provide an ETA for resolution',
      ],
    },
  },
  {
    id: 'conv_003',
    title: 'Login Authentication Failing',
    customer_name: 'Emily Rodriguez',
    category: 'Authentication',
    status: 'escalated',
    created_at: hoursAgo(1),
    updated_at: minutesAgo(5),
    messages: [
      { id: 'm1', role: 'user', text: 'None of our team members can log in. We\'re completely locked out of the system.', timestamp: hoursAgo(1) },
      { id: 'm2', role: 'agent', text: 'That sounds critical. Is it affecting all users or specific accounts?', timestamp: minutesAgo(55) },
      { id: 'm3', role: 'user', text: 'ALL users. Our entire organization of 200+ people is locked out. Production is halted.', timestamp: minutesAgo(50) },
      { id: 'm4', role: 'agent', text: 'I understand the severity. Let me check our auth service status.', timestamp: minutesAgo(45) },
      { id: 'm5', role: 'user', text: 'We are losing thousands of dollars per minute. This needs to be fixed immediately or we will need to consider alternatives.', timestamp: minutesAgo(30) },
      { id: 'm6', role: 'agent', text: 'Our auth service shows normal operation on our end. Can you try clearing cache?', timestamp: minutesAgo(25) },
      { id: 'm7', role: 'user', text: 'We tried that already. This is YOUR problem. The error message specifically says "SSO configuration error". Fix your system!', timestamp: minutesAgo(15) },
    ],
    analysis: {
      risk: 0.95,
      priority: 'P1',
      predicted_escalation: true,
      detection_point: 1,
      emotion: 'ANGRY',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 1, resolution_failure: true, technical_issue: true, sentiment_score: -0.92, urgency: true },
      explanation: [
        'Complete service outage affecting 200+ users',
        'Significant financial impact mentioned',
        'Customer threatening to switch providers',
        'Agent suggestion (clear cache) was ineffective and dismissive',
        'Root cause identified as SSO configuration error',
      ],
      suggested_actions: [
        'Escalate to authentication team immediately',
        'Check SSO/SAML configuration for the customer org',
        'Review recent changes to auth middleware',
        'Provide direct engineering contact',
      ],
    },
  },
  {
    id: 'conv_004',
    title: 'Feature Request — Export',
    customer_name: 'David Kim',
    category: 'Feature Request',
    status: 'resolved',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    messages: [
      { id: 'm1', role: 'user', text: 'Is there any way to export reports to PDF?', timestamp: daysAgo(1) },
      { id: 'm2', role: 'agent', text: 'Currently we support CSV export. PDF export is on our roadmap for Q2. Would CSV work for now?', timestamp: daysAgo(1) },
      { id: 'm3', role: 'user', text: 'CSV works for now. Thanks for the info!', timestamp: daysAgo(1) },
    ],
    analysis: {
      risk: 0.08,
      priority: 'P3',
      predicted_escalation: false,
      detection_point: 0,
      emotion: 'NEUTRAL',
      root_cause: 'NONE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: false, sentiment_score: 0.5, urgency: false },
      explanation: ['Simple feature inquiry', 'Customer satisfied with alternative offered'],
      suggested_actions: ['Log feature request for tracking', 'Add to Q2 roadmap priority list'],
    },
  },
  {
    id: 'conv_005',
    title: 'Billing Discrepancy',
    customer_name: 'Jessica Patel',
    category: 'Billing',
    status: 'active',
    created_at: hoursAgo(6),
    updated_at: hoursAgo(2),
    messages: [
      { id: 'm1', role: 'user', text: 'I was overcharged $2,500 on my last invoice. This is not what we agreed to.', timestamp: hoursAgo(6) },
      { id: 'm2', role: 'agent', text: 'I apologize for the inconvenience. Can you share your account ID so I can review?', timestamp: hoursAgo(5.8) },
      { id: 'm3', role: 'user', text: 'Account ID is ACCT-8847. I\'ve been overcharged for the last 2 months actually.', timestamp: hoursAgo(5.5) },
      { id: 'm4', role: 'agent', text: 'Let me look into this. It may take some time to audit 2 months of billing.', timestamp: hoursAgo(5.3) },
      { id: 'm5', role: 'user', text: 'It\'s been 3 hours with no update. I need this resolved today.', timestamp: hoursAgo(2) },
    ],
    analysis: {
      risk: 0.72,
      priority: 'P2',
      predicted_escalation: true,
      detection_point: 4,
      emotion: 'FRUSTRATED',
      root_cause: 'RESOLUTION_FAILURE',
      signals: { repetition: 1, resolution_failure: true, technical_issue: false, sentiment_score: -0.6, urgency: true },
      explanation: [
        'Billing error spanning multiple months',
        'Significant financial amount ($2,500)',
        'No resolution after 3+ hours',
        'Customer urgency increasing',
      ],
      suggested_actions: [
        'Escalate to billing team for immediate audit',
        'Issue provisional credit while investigating',
        'Provide status update within 30 minutes',
      ],
    },
  },
  {
    id: 'conv_006',
    title: 'Database Migration Help',
    customer_name: 'Alex Johnson',
    category: 'Technical',
    status: 'resolved',
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    messages: [
      { id: 'm1', role: 'user', text: 'We need help migrating our database to the new schema. Is there documentation available?', timestamp: daysAgo(2) },
      { id: 'm2', role: 'agent', text: 'Yes! Here\'s our migration guide: docs.example.com/migration. We also have a step-by-step tutorial.', timestamp: daysAgo(2) },
      { id: 'm3', role: 'user', text: 'Perfect, the guide looks comprehensive. One question — do we need to schedule downtime?', timestamp: daysAgo(2) },
      { id: 'm4', role: 'agent', text: 'For databases under 50GB, zero-downtime migration is supported. For larger databases, we recommend a 15-minute maintenance window. What\'s your DB size?', timestamp: daysAgo(2) },
      { id: 'm5', role: 'user', text: 'We\'re at 30GB so zero-downtime works! Thanks for the quick help.', timestamp: daysAgo(2) },
    ],
    analysis: {
      risk: 0.05,
      priority: 'P3',
      predicted_escalation: false,
      detection_point: 0,
      emotion: 'SATISFIED',
      root_cause: 'NONE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: false, sentiment_score: 0.8, urgency: false },
      explanation: ['Smooth interaction with quick resolution', 'Positive customer sentiment throughout'],
      suggested_actions: ['Follow up post-migration to ensure success'],
    },
  },
  {
    id: 'conv_007',
    title: 'Webhook Failures',
    customer_name: 'Rachel Wright',
    category: 'Integration',
    status: 'active',
    created_at: hoursAgo(8),
    updated_at: hoursAgo(3),
    messages: [
      { id: 'm1', role: 'user', text: 'Our webhooks have been failing silently for the past week. We just noticed we missed thousands of events.', timestamp: hoursAgo(8) },
      { id: 'm2', role: 'agent', text: 'I\'m sorry about that. Let me check your webhook delivery logs.', timestamp: hoursAgo(7.8) },
      { id: 'm3', role: 'user', text: 'We\'ve lost crucial data because of this. Is there a way to replay the missed events?', timestamp: hoursAgo(7.5) },
      { id: 'm4', role: 'agent', text: 'We do have event replay capability. Let me first identify the root cause of the failures.', timestamp: hoursAgo(7.3) },
      { id: 'm5', role: 'user', text: 'Any findings? This is impacting our data pipeline severely.', timestamp: hoursAgo(5) },
      { id: 'm6', role: 'agent', text: 'Still investigating. The logs show intermittent timeout errors to your endpoint.', timestamp: hoursAgo(4.5) },
      { id: 'm7', role: 'user', text: 'Our endpoint is fine — we tested it. The timeouts are happening too quickly on your side. Your default timeout is 3 seconds which isn\'t configurable.', timestamp: hoursAgo(3) },
    ],
    analysis: {
      risk: 0.78,
      priority: 'P1',
      predicted_escalation: true,
      detection_point: 3,
      emotion: 'FRUSTRATED',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 1, resolution_failure: true, technical_issue: true, sentiment_score: -0.55, urgency: true },
      explanation: [
        'Data loss over extended period (1 week)',
        'System limitation identified (non-configurable timeout)',
        'Customer has done their own root cause analysis',
        'No fix offered yet',
      ],
      suggested_actions: [
        'Enable event replay for missed events',
        'Increase webhook timeout for this customer',
        'File feature request for configurable timeout',
        'Provide interim monitoring solution',
      ],
    },
  },
  {
    id: 'conv_008',
    title: 'Password Reset Not Working',
    customer_name: 'Tom Baker',
    category: 'Authentication',
    status: 'resolved',
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    messages: [
      { id: 'm1', role: 'user', text: 'I can\'t reset my password. The email never arrives.', timestamp: daysAgo(3) },
      { id: 'm2', role: 'agent', text: 'Have you checked your spam folder?', timestamp: daysAgo(3) },
      { id: 'm3', role: 'user', text: 'Yes, checked everywhere. Nothing.', timestamp: daysAgo(3) },
      { id: 'm4', role: 'agent', text: 'I\'ve manually triggered a reset email to your address. You should receive it within 2 minutes.', timestamp: daysAgo(3) },
      { id: 'm5', role: 'user', text: 'Got it! Working now. Thanks!', timestamp: daysAgo(3) },
    ],
    analysis: {
      risk: 0.15,
      priority: 'P3',
      predicted_escalation: false,
      detection_point: 0,
      emotion: 'NEUTRAL',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: true, sentiment_score: 0.3, urgency: false },
      explanation: ['Email delivery issue resolved with manual trigger', 'Quick resolution'],
      suggested_actions: ['Investigate email delivery pipeline for this domain'],
    },
  },
  {
    id: 'conv_009',
    title: 'Rate Limiting Blocking Legitimate Traffic',
    customer_name: 'Lisa Chang',
    category: 'Technical',
    status: 'escalated',
    created_at: hoursAgo(3),
    updated_at: minutesAgo(30),
    messages: [
      { id: 'm1', role: 'user', text: 'Your rate limiter is blocking our legitimate API traffic. We\'re getting 429 errors on normal usage.', timestamp: hoursAgo(3) },
      { id: 'm2', role: 'agent', text: 'I see. What\'s your current API usage volume?', timestamp: hoursAgo(2.8) },
      { id: 'm3', role: 'user', text: 'About 500 requests per minute, well within our Enterprise plan limit of 2000/min.', timestamp: hoursAgo(2.5) },
      { id: 'm4', role: 'agent', text: 'You\'re right, that should be within limits. I\'ll check with our platform team.', timestamp: hoursAgo(2.3) },
      { id: 'm5', role: 'user', text: 'We\'ve had to implement client-side throttling as a workaround. This is costing us development time.', timestamp: hoursAgo(1) },
      { id: 'm6', role: 'user', text: 'Update: we found that your rate limiter is counting OPTIONS preflight requests. This is a bug, not a feature.', timestamp: minutesAgo(30) },
    ],
    analysis: {
      risk: 0.82,
      priority: 'P1',
      predicted_escalation: true,
      detection_point: 3,
      emotion: 'FRUSTRATED',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 0, resolution_failure: true, technical_issue: true, sentiment_score: -0.6, urgency: true },
      explanation: [
        'Legitimate traffic being blocked by system bug',
        'Customer identified the root cause themselves',
        'Development cost impact on customer',
        'Enterprise-tier customer with active SLA',
      ],
      suggested_actions: [
        'File critical bug: rate limiter counting OPTIONS requests',
        'Temporarily whitelist customer IP range',
        'Deploy hotfix to exclude preflight requests',
        'Credit customer for impacted period',
      ],
    },
  },
  {
    id: 'conv_010',
    title: 'Data Export Taking Too Long',
    customer_name: 'James Wilson',
    category: 'Performance',
    status: 'active',
    created_at: hoursAgo(5),
    updated_at: hoursAgo(4),
    messages: [
      { id: 'm1', role: 'user', text: 'Trying to export 6 months of data but the export keeps timing out after 30 minutes.', timestamp: hoursAgo(5) },
      { id: 'm2', role: 'agent', text: 'Large exports can take time. Have you tried breaking it into monthly chunks?', timestamp: hoursAgo(4.8) },
      { id: 'm3', role: 'user', text: 'I need it all in one file for our compliance audit. Is there a way to increase the timeout?', timestamp: hoursAgo(4.5) },
      { id: 'm4', role: 'agent', text: 'Unfortunately the timeout is fixed. I can submit a request to generate the export on our backend and email it to you.', timestamp: hoursAgo(4) },
    ],
    analysis: {
      risk: 0.42,
      priority: 'P2',
      predicted_escalation: false,
      detection_point: 0,
      emotion: 'NEUTRAL',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: true, sentiment_score: -0.1, urgency: false },
      explanation: ['System limitation for large exports', 'Workaround offered and being considered'],
      suggested_actions: ['Generate backend export for customer', 'Add large export capability to roadmap'],
    },
  },
  {
    id: 'conv_011',
    title: 'Mobile App Crashing',
    customer_name: 'Nina Petrov',
    category: 'Mobile',
    status: 'active',
    created_at: hoursAgo(7),
    updated_at: hoursAgo(2),
    messages: [
      { id: 'm1', role: 'user', text: 'The mobile app crashes every time I try to view the report section. iOS 18.', timestamp: hoursAgo(7) },
      { id: 'm2', role: 'agent', text: 'Sorry about that. Have you tried reinstalling the app?', timestamp: hoursAgo(6.5) },
      { id: 'm3', role: 'user', text: 'Yes, reinstalled twice. Same crash.', timestamp: hoursAgo(6) },
      { id: 'm4', role: 'agent', text: 'Can you send us the crash log from Settings > Privacy > Analytics?', timestamp: hoursAgo(5.5) },
      { id: 'm5', role: 'user', text: 'Sent. Multiple users on our team are seeing this on iOS 18.', timestamp: hoursAgo(4) },
    ],
    analysis: {
      risk: 0.55,
      priority: 'P2',
      predicted_escalation: false,
      detection_point: 4,
      emotion: 'FRUSTRATED',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: true, sentiment_score: -0.3, urgency: false },
      explanation: ['Reproducible crash on specific OS version', 'Multiple users affected', 'Customer cooperating with diagnostics'],
      suggested_actions: ['Review crash logs', 'Test on iOS 18 simulator', 'Check for iOS 18 compatibility issues'],
    },
  },
  {
    id: 'conv_012',
    title: 'SSO Integration Setup',
    customer_name: 'Chris Anderson',
    category: 'Integration',
    status: 'resolved',
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    messages: [
      { id: 'm1', role: 'user', text: 'Need help setting up SAML SSO with Okta.', timestamp: daysAgo(4) },
      { id: 'm2', role: 'agent', text: 'Sure! I can walk you through the setup. First, go to Admin > Security > SSO Configuration.', timestamp: daysAgo(4) },
      { id: 'm3', role: 'user', text: 'Done. What metadata URL do I enter?', timestamp: daysAgo(4) },
      { id: 'm4', role: 'agent', text: 'Enter your Okta metadata URL which looks like: https://your-domain.okta.com/app/APP_ID/sso/saml/metadata', timestamp: daysAgo(4) },
      { id: 'm5', role: 'user', text: 'Got it configured. SSO is working perfectly now. Thanks for the guidance!', timestamp: daysAgo(4) },
    ],
    analysis: {
      risk: 0.03,
      priority: 'P3',
      predicted_escalation: false,
      detection_point: 0,
      emotion: 'SATISFIED',
      root_cause: 'NONE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: false, sentiment_score: 0.9, urgency: false },
      explanation: ['Smooth onboarding interaction', 'Successful configuration with guidance'],
      suggested_actions: ['Send follow-up SSO best practices doc'],
    },
  },
  {
    id: 'conv_013',
    title: 'Data Not Syncing',
    customer_name: 'Maria Gonzalez',
    category: 'Data',
    status: 'active',
    created_at: hoursAgo(10),
    updated_at: hoursAgo(1),
    messages: [
      { id: 'm1', role: 'user', text: 'Our data sync with Salesforce stopped working 2 days ago. We just noticed.', timestamp: hoursAgo(10) },
      { id: 'm2', role: 'agent', text: 'I can check your integration status. One moment.', timestamp: hoursAgo(9.5) },
      { id: 'm3', role: 'user', text: 'We have 48 hours of missing data that needs to be recovered.', timestamp: hoursAgo(9) },
      { id: 'm4', role: 'agent', text: 'The sync failed due to an expired API token. You\'ll need to re-authenticate in Settings > Integrations.', timestamp: hoursAgo(8) },
      { id: 'm5', role: 'user', text: 'Token refreshed. But what about the 48 hours of missed data?', timestamp: hoursAgo(6) },
      { id: 'm6', role: 'agent', text: 'I\'ve initiated a backfill for the missing period. It should complete within 2-4 hours.', timestamp: hoursAgo(5) },
      { id: 'm7', role: 'user', text: 'It\'s been 4 hours and only 30% is synced. Is this normal?', timestamp: hoursAgo(1) },
    ],
    analysis: {
      risk: 0.65,
      priority: 'P2',
      predicted_escalation: false,
      detection_point: 5,
      emotion: 'FRUSTRATED',
      root_cause: 'RESOLUTION_FAILURE',
      signals: { repetition: 1, resolution_failure: true, technical_issue: true, sentiment_score: -0.4, urgency: false },
      explanation: ['Data loss over 48 hours', 'Backfill taking longer than estimated', 'Customer patience wearing thin'],
      suggested_actions: ['Check backfill queue priority', 'Provide updated ETA', 'Monitor sync completion'],
    },
  },
  {
    id: 'conv_014',
    title: 'UI Bug on Chrome',
    customer_name: 'Robert Lee',
    category: 'Bug',
    status: 'resolved',
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    messages: [
      { id: 'm1', role: 'user', text: 'The sidebar menu overlaps the main content area on Chrome 120.', timestamp: daysAgo(5) },
      { id: 'm2', role: 'agent', text: 'Thank you for reporting this. We\'re aware of this CSS issue and a fix will be deployed today.', timestamp: daysAgo(5) },
      { id: 'm3', role: 'user', text: 'Great, looking forward to the fix. Thanks!', timestamp: daysAgo(5) },
    ],
    analysis: {
      risk: 0.12,
      priority: 'P3',
      predicted_escalation: false,
      detection_point: 0,
      emotion: 'NEUTRAL',
      root_cause: 'TECHNICAL_ISSUE',
      signals: { repetition: 0, resolution_failure: false, technical_issue: true, sentiment_score: 0.4, urgency: false },
      explanation: ['Known bug with fix incoming', 'Customer accepted timeline'],
      suggested_actions: ['Verify fix deployed', 'Follow up with customer'],
    },
  },
  {
    id: 'conv_015',
    title: 'Account Suspension Appeal',
    customer_name: 'Amanda Foster',
    category: 'Account',
    status: 'escalated',
    created_at: hoursAgo(12),
    updated_at: hoursAgo(1),
    messages: [
      { id: 'm1', role: 'user', text: 'My account was suspended without any warning or explanation. I need this resolved immediately.', timestamp: hoursAgo(12) },
      { id: 'm2', role: 'agent', text: 'I can see your account was flagged by our automated system. Let me review the details.', timestamp: hoursAgo(11) },
      { id: 'm3', role: 'user', text: 'I haven\'t violated any terms. This is completely unjustified.', timestamp: hoursAgo(10) },
      { id: 'm4', role: 'agent', text: 'It appears there was unusual activity detected from your account. As a security measure, it was temporarily suspended.', timestamp: hoursAgo(9) },
      { id: 'm5', role: 'user', text: 'That was a legitimate batch import we scheduled! Your system should know the difference. This is the second time this has happened.', timestamp: hoursAgo(8) },
      { id: 'm6', role: 'agent', text: 'I understand your frustration. I\'ll submit a manual review request.', timestamp: hoursAgo(7) },
      { id: 'm7', role: 'user', text: 'It\'s been 6 hours since you submitted the review. My team of 50 people can\'t access any data. We\'re losing clients.', timestamp: hoursAgo(1) },
    ],
    analysis: {
      risk: 0.88,
      priority: 'P1',
      predicted_escalation: true,
      detection_point: 3,
      emotion: 'ANGRY',
      root_cause: 'REPEATED_ISSUE',
      signals: { repetition: 2, resolution_failure: true, technical_issue: false, sentiment_score: -0.8, urgency: true },
      explanation: [
        'False positive account suspension — legitimate activity',
        'Recurring issue ("second time this has happened")',
        'Significant business impact — 50 users blocked',
        'Review process taking too long (6+ hours)',
        'Customer experiencing financial losses',
      ],
      suggested_actions: [
        'Immediately restore account access',
        'Whitelist batch import IP/pattern',
        'Review automated suspension rules',
        'Escalate to account management for retention risk',
      ],
    },
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_conversations: 1247,
  escalation_rate: 18.5,
  avg_risk_score: 0.42,
  active_alerts: 7,
  resolved_today: 34,
  avg_response_time: '4.2 min',
};

// ─── Alerts ───────────────────────────────────────────────────
export const MOCK_ALERTS: AlertItem[] = [
  { id: 'alert_1', conversation_id: 'conv_003', customer_name: 'Emily Rodriguez', risk: 0.95, priority: 'P1', message: 'Complete authentication lockout — 200+ users affected', timestamp: minutesAgo(5), type: 'escalation' },
  { id: 'alert_2', conversation_id: 'conv_001', customer_name: 'Sarah Chen', risk: 0.92, priority: 'P1', message: 'Recurring API gateway 502 errors — payment processing impacted', timestamp: minutesAgo(15), type: 'escalation' },
  { id: 'alert_3', conversation_id: 'conv_015', customer_name: 'Amanda Foster', risk: 0.88, priority: 'P1', message: 'False positive account suspension — team of 50 blocked', timestamp: hoursAgo(1), type: 'risk_spike' },
  { id: 'alert_4', conversation_id: 'conv_009', customer_name: 'Lisa Chang', risk: 0.82, priority: 'P1', message: 'Rate limiter bug blocking legitimate API traffic', timestamp: minutesAgo(30), type: 'signal_detected' },
  { id: 'alert_5', conversation_id: 'conv_007', customer_name: 'Rachel Wright', risk: 0.78, priority: 'P1', message: 'Silent webhook failures — 1 week of lost data', timestamp: hoursAgo(3), type: 'escalation' },
  { id: 'alert_6', conversation_id: 'conv_005', customer_name: 'Jessica Patel', risk: 0.72, priority: 'P2', message: 'Billing discrepancy — $2,500 overcharge for 2 months', timestamp: hoursAgo(2), type: 'risk_spike' },
  { id: 'alert_7', conversation_id: 'conv_013', customer_name: 'Maria Gonzalez', risk: 0.65, priority: 'P2', message: 'Data sync backfill taking longer than estimated', timestamp: hoursAgo(1), type: 'signal_detected' },
];

// ─── Time Series Data ─────────────────────────────────────────
export const MOCK_RISK_TREND: TimeSeriesPoint[] = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - (29 - i) * 86400000).toISOString().split('T')[0],
  value: +(0.3 + Math.sin(i / 5) * 0.15 + Math.random() * 0.1).toFixed(2),
}));

export const MOCK_ESCALATION_TREND: TimeSeriesPoint[] = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - (29 - i) * 86400000).toISOString().split('T')[0],
  value: Math.floor(3 + Math.sin(i / 7) * 2 + Math.random() * 3),
}));

export const MOCK_VOLUME_TREND: TimeSeriesPoint[] = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - (29 - i) * 86400000).toISOString().split('T')[0],
  value: Math.floor(30 + Math.sin(i / 4) * 10 + Math.random() * 8),
}));

// ─── Signal Frequencies ──────────────────────────────────────
export const MOCK_SIGNAL_FREQUENCIES: SignalFrequency[] = [
  { signal: 'Technical Issue', count: 187, percentage: 38 },
  { signal: 'Resolution Failure', count: 143, percentage: 29 },
  { signal: 'Urgency Detection', count: 98, percentage: 20 },
  { signal: 'Repetition', count: 76, percentage: 15 },
  { signal: 'Negative Sentiment', count: 201, percentage: 41 },
];

// ─── Failure Breakdown ───────────────────────────────────────
export const MOCK_FAILURE_BREAKDOWN = [
  { name: 'Resolution Failure', value: 35, color: '#EF4444' },
  { name: 'Technical Issue', value: 28, color: '#F59E0B' },
  { name: 'Poor Communication', value: 18, color: '#8B5CF6' },
  { name: 'Repeated Issue', value: 12, color: '#3B82F6' },
  { name: 'SLA Breach', value: 7, color: '#06B6D4' },
];

// ─── Evaluation Metrics ──────────────────────────────────────
export const MOCK_EVALUATION_METRICS: EvaluationMetrics = {
  precision: 0.89,
  recall: 0.94,
  f1_score: 0.91,
  early_detection_score: 0.85,
  false_positive_rate: 0.08,
  accuracy: 0.92,
  confusion_matrix: {
    tp: 142,
    fp: 18,
    fn: 9,
    tn: 231,
  },
  roc_data: [
    { fpr: 0, tpr: 0 },
    { fpr: 0.02, tpr: 0.35 },
    { fpr: 0.05, tpr: 0.58 },
    { fpr: 0.08, tpr: 0.72 },
    { fpr: 0.1, tpr: 0.79 },
    { fpr: 0.15, tpr: 0.85 },
    { fpr: 0.2, tpr: 0.89 },
    { fpr: 0.25, tpr: 0.91 },
    { fpr: 0.3, tpr: 0.93 },
    { fpr: 0.4, tpr: 0.95 },
    { fpr: 0.5, tpr: 0.96 },
    { fpr: 0.6, tpr: 0.97 },
    { fpr: 0.7, tpr: 0.98 },
    { fpr: 0.8, tpr: 0.99 },
    { fpr: 0.9, tpr: 0.995 },
    { fpr: 1, tpr: 1 },
  ],
  detection_points: [
    { conversation_id: 'conv_001', predicted_turn: 3, actual_turn: 7 },
    { conversation_id: 'conv_003', predicted_turn: 1, actual_turn: 5 },
    { conversation_id: 'conv_005', predicted_turn: 4, actual_turn: 5 },
    { conversation_id: 'conv_007', predicted_turn: 3, actual_turn: 6 },
    { conversation_id: 'conv_009', predicted_turn: 3, actual_turn: 5 },
    { conversation_id: 'conv_015', predicted_turn: 3, actual_turn: 7 },
  ],
};

// ─── Tickets ──────────────────────────────────────────────────
export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'TKT-4281',
    customer_name: 'Sarah Chen',
    email: 'sarah.chen@techcorp.io',
    subject: 'API Gateway 502 Errors — Payment Processing Down',
    priority: 'P1',
    sentiment: 'NEGATIVE',
    status: 'escalated',
    ai_summary: 'Recurring 502 errors on /api/v2/payments affecting revenue. Third occurrence this month. Customer requesting manager escalation.',
    ai_transcript_snippet: '"This is the third time this month! Our customers are unable to make payments..."',
    category: 'Technical',
    risk: 0.92,
    created_at: '2h ago',
    assigned_agent: 'James Park',
  },
  {
    id: 'TKT-4279',
    customer_name: 'Emily Rodriguez',
    email: 'e.rodriguez@globalfinance.com',
    subject: 'Complete Authentication Lockout — 200+ Users',
    priority: 'P1',
    sentiment: 'NEGATIVE',
    status: 'escalated',
    ai_summary: 'Organization-wide SSO failure. 200+ users locked out. Customer threatens to evaluate competitors. Root cause: SSO config error.',
    ai_transcript_snippet: '"We are losing thousands of dollars per minute. This needs to be fixed immediately..."',
    category: 'Authentication',
    risk: 0.95,
    created_at: '1h ago',
    assigned_agent: 'Maya Singh',
  },
  {
    id: 'TKT-4277',
    customer_name: 'Amanda Foster',
    email: 'afoster@nexadigital.co',
    subject: 'Account Suspended Without Warning — False Positive',
    priority: 'P1',
    sentiment: 'NEGATIVE',
    status: 'escalated',
    ai_summary: 'Automated suspension triggered by legitimate batch import. Second false positive. 50 users blocked for 6+ hours.',
    ai_transcript_snippet: '"That was a legitimate batch import! Your system should know the difference..."',
    category: 'Account',
    risk: 0.88,
    created_at: '12h ago',
    assigned_agent: 'Alex Rivera',
  },
  {
    id: 'TKT-4275',
    customer_name: 'Lisa Chang',
    email: 'lisa.chang@devplatform.io',
    subject: 'Rate Limiter Bug — Blocking Legitimate Traffic',
    priority: 'P1',
    sentiment: 'NEGATIVE',
    status: 'in_progress',
    ai_summary: 'Rate limiter incorrectly counting OPTIONS preflight requests. Customer at 500 req/min vs 2000/min limit. Enterprise plan.',
    ai_transcript_snippet: '"Your rate limiter is counting OPTIONS preflight requests. This is a bug, not a feature."',
    category: 'Technical',
    risk: 0.82,
    created_at: '3h ago',
    assigned_agent: 'James Park',
  },
  {
    id: 'TKT-4273',
    customer_name: 'Jessica Patel',
    email: 'jpatel@retailhub.com',
    subject: 'Billing Discrepancy — $2,500 Overcharge',
    priority: 'P2',
    sentiment: 'NEGATIVE',
    status: 'in_progress',
    ai_summary: 'Overcharged $2,500 on last invoice, suspected overcharges for past 2 months. Awaiting billing audit (3+ hours with no update).',
    ai_transcript_snippet: '"I was overcharged $2,500 on my last invoice. This is not what we agreed to."',
    category: 'Billing',
    risk: 0.72,
    created_at: '6h ago',
    assigned_agent: 'Diana Cruz',
  },
  {
    id: 'TKT-4271',
    customer_name: 'Michael Torres',
    email: 'mtorres@analytics.pro',
    subject: 'Dashboard Loading Slowly After Update',
    priority: 'P2',
    sentiment: 'MIXED',
    status: 'in_progress',
    ai_summary: 'Analytics dashboard taking 15+ seconds to load after recent platform update. Performance regression confirmed.',
    ai_transcript_snippet: '"Our dashboard is taking 15+ seconds to load. It used to be instant."',
    category: 'Performance',
    risk: 0.58,
    created_at: '4h ago',
    assigned_agent: 'Maya Singh',
  },
  {
    id: 'TKT-4269',
    customer_name: 'Rachel Wright',
    email: 'rwright@dataflow.co',
    subject: 'Webhook Failures — 1 Week of Lost Data',
    priority: 'P1',
    sentiment: 'NEGATIVE',
    status: 'in_progress',
    ai_summary: 'Silent webhook failures for 7 days. Thousands of missed events. Root cause: 3-second non-configurable timeout too aggressive.',
    ai_transcript_snippet: '"Our webhooks have been failing silently for the past week. We just noticed we missed thousands of events."',
    category: 'Integration',
    risk: 0.78,
    created_at: '8h ago',
    assigned_agent: 'Alex Rivera',
  },
  {
    id: 'TKT-4267',
    customer_name: 'David Kim',
    email: 'dkim@startuplab.io',
    subject: 'Feature Request — PDF Export',
    priority: 'P3',
    sentiment: 'POSITIVE',
    status: 'resolved',
    ai_summary: 'Customer asked about PDF export capability. Informed of CSV alternative and Q2 roadmap. Customer satisfied.',
    ai_transcript_snippet: '"CSV works for now. Thanks for the info!"',
    category: 'Feature Request',
    risk: 0.08,
    created_at: '1d ago',
    assigned_agent: 'Diana Cruz',
  },
  {
    id: 'TKT-4265',
    customer_name: 'Maria Gonzalez',
    email: 'mgonzalez@cloudsync.net',
    subject: 'Salesforce Data Sync Stopped — 48h Data Gap',
    priority: 'P2',
    sentiment: 'MIXED',
    status: 'waiting',
    ai_summary: 'Data sync failure due to expired API token. Token refreshed. Backfill initiated but taking longer than 4-hour ETA (only 30% done).',
    ai_transcript_snippet: '"It\'s been 4 hours and only 30% is synced. Is this normal?"',
    category: 'Data',
    risk: 0.65,
    created_at: '10h ago',
    assigned_agent: 'James Park',
  },
  {
    id: 'TKT-4263',
    customer_name: 'Nina Petrov',
    email: 'nina.p@mobileworks.app',
    subject: 'Mobile App Crashing on iOS 18 — Report Section',
    priority: 'P2',
    sentiment: 'NEUTRAL',
    status: 'in_progress',
    ai_summary: 'Reproducible crash in report section on iOS 18. Multiple team members affected. Crash logs submitted.',
    ai_transcript_snippet: '"Multiple users on our team are seeing this on iOS 18."',
    category: 'Mobile',
    risk: 0.55,
    created_at: '7h ago',
    assigned_agent: 'Maya Singh',
  },
];
